DEFAULT_EDGAR_ISSUER_FILTER = {
    "blocked_ciks": [
        "0001889983",
        "0001900679",
        "0001865248",
        "0001970509",
        "0002000775",
        "0002028516",
        "0002050501",
        "0002079013",
        "0002080087",
        "0002112446",
    ],
    "name_patterns_ci": [
        r"\bspac\b",
        r"\bspecial\s+purpose\s+acquisition\b",
        r"\bacquisition\s+corp(?:oration)?\b",
        r"\bacquisition\s+co\.?\b",
        r"\bholdings\s+trust\b",
        r"\bblank\s+check\b",
    ],
    "description_patterns_ci": [
        r"\bshell\s+company\b",
        r"\bblank\s+check\s+company\b",
        r"\bspecial\s+purpose\s+acquisition\s+company\b",
        r"formed\s+for\s+the\s+purpose\s+of\s+effecting\s+a\s+merger",
        r"formed\s+for\s+the\s+purpose\s+of\s+effecting\s+a\s+share\s+exchange",
        r"formed\s+for\s+the\s+purpose\s+of\s+effecting\s+a\s+business\s+combination",
        r"\bconsummation\s+of\s+the\s+initial\s+business\s+combination\b",
        r"\btrust\s+account\b",
    ],
    "allowlist_tickers": ["RPAY"],
    "allowlist_ciks": ["0001720592"],
}
